import{S as b,i as n,a as f}from"./assets/vendor-Qob_5Ba8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&y(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function y(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const u=new b(".gallery-item",{captionsData:"alt",captionDelay:250}),L=document.getElementById("search-form"),c=document.getElementById("gallery"),p=document.getElementById("loading-spinner"),a=document.getElementById("load-more");let i=1;const g=40;let m=0,l="";document.addEventListener("DOMContentLoaded",()=>{L.addEventListener("submit",async o=>{if(o.preventDefault(),l=document.getElementById("search-input").value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search term!"});return}i=1,a.style.display="none";try{p.style.display="block";const r=(await f.get(`https://pixabay.com/api/?key=46164011-db8308970fd829f53e85acb75&q=${l}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${g}`)).data;if(m=r.totalHits,r.hits.length===0){n.error({title:"Warning",message:"Image not found. Please try again!"});return}c.innerHTML="",h(r.hits),r.hits.length>=g&&c.children.length<m&&(a.style.display="block"),u.refresh()}catch(e){p.style.display="none",n.error({title:"Warning",message:"A problem has occurred. Please try again!"}),console.error("A problem has occurred:",e)}finally{p.style.display="none"}}),a.addEventListener("click",async()=>{i+=1;try{const e=(await f.get(`https://pixabay.com/api/?key=46164011-db8308970fd829f53e85acb75&q=${l}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${g}`)).data;h(e.hits),c.children.length>=m&&(a.style.display="none",n.info({message:"We're sorry, but you've reached the end of search results."})),u.refresh()}catch(o){n.error({title:"Warning",message:"A problem has occurred. Please try again!"}),console.error("A problem has occurred:",o)}})});function h(o){o.forEach(e=>{const r=document.createElement("a");r.href=e.largeImageURL,r.classList.add("gallery-item"),r.innerHTML=`
          <li id="gallery-items">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </li>
          <div class="gallery-items-info">
            <p class="gallery-items-info-alt"><strong>Likes:</strong> ${e.likes}</p>
            <p class="gallery-items-info-alt"><strong>Comments:</strong> ${e.comments}</p>
            <p class="gallery-items-info-alt"><strong>Views:</strong> ${e.views}</p>
            <p class="gallery-items-info-alt"><strong>Downloads:</strong> ${e.downloads}</p>
          </div>
        `,c.appendChild(r)})}
//# sourceMappingURL=index.js.map
