import{S as L,i as o,a as y}from"./assets/vendor-Qob_5Ba8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&m(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function m(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const g=new L(".gallery-item",{captionsData:"alt",captionDelay:250}),b=document.getElementById("search-form"),c=document.getElementById("gallery"),p=document.getElementById("loading-spinner"),a=document.getElementById("load-more");let i=1;const u=40;let f=0,l="";document.addEventListener("DOMContentLoaded",()=>{b.addEventListener("submit",async n=>{if(n.preventDefault(),l=document.getElementById("search-input").value.trim(),!l){o.warning({title:"Uyarı",message:"Lütfen bir arama terimi girin!"});return}i=1,a.style.display="none";try{p.style.display="block";const r=(await y.get(`https://pixabay.com/api/?key=46164011-db8308970fd829f53e85acb75&q=${l}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${u}`)).data;if(f=r.totalHits,r.hits.length===0){o.error({title:"Hata",message:"Görsel bulunamadı. Lütfen tekrar deneyin!"});return}c.innerHTML="",h(r.hits),r.hits.length>=u&&c.children.length<f&&(a.style.display="block"),g.refresh()}catch(e){p.style.display="none",o.error({title:"Hata",message:"Bir sorun oluştu. Lütfen tekrar deneyin!"}),console.error("Bir hata oluştu:",e)}finally{p.style.display="none"}}),a.addEventListener("click",async()=>{i+=1;try{const e=(await y.get(`https://pixabay.com/api/?key=46164011-db8308970fd829f53e85acb75&q=${l}&image_type=photo&orientation=horizontal&safesearch=true&page=${i}&per_page=${u}`)).data;h(e.hits),c.children.length>=f&&(a.style.display="none",o.info({message:"We're sorry, but you've reached the end of search results."})),g.refresh()}catch(n){o.error({title:"Hata",message:"Bir sorun oluştu. Lütfen tekrar deneyin!"}),console.error("Bir hata oluştu:",n)}})});function h(n){n.forEach(e=>{const r=document.createElement("a");r.href=e.largeImageURL,r.classList.add("gallery-item"),r.innerHTML=`
          <li id="gallery-items">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </li>
          <div class="gallery-items-info">
            <p class="gallery-items-info-alt"><strong>Likes:</strong> ${e.likes}</p>
            <p class="gallery-items-info-alt"><strong>Comments:</strong> ${e.comments}</p>
            <p class="gallery-items-info-alt"><strong>Views:</strong> ${e.views}</p>
            <p class="gallery-items-info-alt"><strong>Downloads:</strong> ${e.downloads}</p>
          </div>
        `,c.appendChild(r)})}
//# sourceMappingURL=index.js.map
